apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-net-http-hello-ktfs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-net-http-hello-ktfs
    app.kubernetes.io/part-of: go
  name: go-net-http-hello-ktfs
  namespace: burrzinga-hac-tenant
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: go-net-http-hello-ktfs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: go-net-http-hello-ktfs
    spec:
      containers:
      - image: go-image:latest
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
