apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-net-http-hello-ktfs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-net-http-hello-ktfs
    app.kubernetes.io/part-of: go
  name: go-net-http-hello-ktfs
  namespace: burrzinga-hac-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: go-net-http-hello-ktfs
status:
  loadBalancer: {}
